# Generated by Django 4.2.5 on 2023-09-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_image',
            field=models.ImageField(default=None, upload_to='users/covers'),
            preserve_default=False,
        ),
    ]
