# Generated by Django 4.2.5 on 2023-09-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='users/covers'),
        ),
    ]
